# AIOps Infrastructure Monitoring - Python Dependencies
# Install with: pip install -r requirements.txt

# ============================================================================
# Core Data Processing
# ============================================================================
numpy>=1.24.0,<2.0.0
pandas>=2.0.0,<3.0.0

# ============================================================================
# Time-Series Database
# ============================================================================
influxdb-client>=1.36.0,<2.0.0

# ============================================================================
# Machine Learning - Anomaly Detection
# ============================================================================
scikit-learn>=1.3.0,<2.0.0
joblib>=1.3.0,<2.0.0

# ============================================================================
# Deep Learning - LSTM Predictions
# ============================================================================
tensorflow>=2.13.0,<3.0.0
keras>=2.13.0,<3.0.0

# ============================================================================
# Visualization
# ============================================================================
matplotlib>=3.7.0,<4.0.0
seaborn>=0.12.0,<1.0.0
plotly>=5.14.0,<6.0.0
kaleido>=0.2.1,<1.0.0

# ============================================================================
# Web Framework (for dashboards)
# ============================================================================
flask>=2.3.0,<3.0.0
flask-cors>=4.0.0,<5.0.0

# ============================================================================
# HTTP Requests (for Slack/PagerDuty)
# ============================================================================
requests>=2.31.0,<3.0.0
urllib3>=2.0.0,<3.0.0

# ============================================================================
# AWS Integration
# ============================================================================
boto3>=1.28.0,<2.0.0
botocore>=1.31.0,<2.0.0

# ============================================================================
# Configuration & Environment
# ============================================================================
python-dotenv>=1.0.0,<2.0.0
pyyaml>=6.0,<7.0

# ============================================================================
# Date/Time Utilities
# ============================================================================
python-dateutil>=2.8.0,<3.0.0
pytz>=2023.3

# ============================================================================
# Testing (optional - for development)
# ============================================================================
# pytest>=7.4.0,<8.0.0
# pytest-cov>=4.1.0,<5.0.0
# pytest-mock>=3.11.0,<4.0.0

# ============================================================================
# Code Quality (optional - for development)
# ============================================================================
# black>=23.7.0,<24.0.0
# flake8>=6.1.0,<7.0.0
# pylint>=2.17.0,<3.0.0
# mypy>=1.5.0,<2.0.0

# ============================================================================
# Documentation (optional)
# ============================================================================
# sphinx>=7.1.0,<8.0.0
# sphinx-rtd-theme>=1.3.0,<2.0.0